common: fix `-Wrange-loop-analysis` error on Envoy Mobile (#13342)
Envoy Mobile is failing compilation with this error:

```
external/envoy/source/common/http/header_map_impl.cc:506:23: error: loop variable 'values_it' of type 'const std::__1::__list_iterator<Envoy::Http::HeaderMapImpl::HeaderEntryImpl, void *>' creates a copy from type 'const std::__1::__list_iterator<Envoy::Http::HeaderMapImpl::HeaderEntryImpl, void *>' [-Werror,-Wrange-loop-analysis]
      for (const auto values_it : v) {
                      ^
external/envoy/source/common/http/header_map_impl.cc:506:12: note: use reference type 'const std::__1::__list_iterator<Envoy::Http::HeaderMapImpl::HeaderEntryImpl, void *> &' to prevent copying
      for (const auto values_it : v) {
           ^~~~~~~~~~~~~~~~~~~~~~
                      &
```

This regression was introduced in https://github.com/envoyproxy/envoy/commit/25f9a61013d2b7694dbf4944f0f8be10e009775b.

Signed-off-by: Michael Rebello <me@michaelrebello.com>